### ISSUE TITLE
Observable<UpdateAvailableEvent> is deprecated: 

### ISSUE THREAD

**Issue by VashJuan** [PacktPublishing/Angular-Projects-Second-Edition#7]
https://github.com/PacktPublishing/Angular-Projects-Second-Edition/blob/main/Chapter04/src/app/app.component.ts uses deprecated "available", and gets the following message: 

(property) SwUpdate.available: Observable<UpdateAvailableEvent>
Emits an UpdateAvailableEvent event whenever a new app version is available.

@deprecated
Use versionUpdates instead.

The of behavior available can be rebuild by filtering for the VersionReadyEvent:

import {filter, map} from 'rxjs/operators';
// ...
const updatesAvailable = swUpdate.versionUpdates.pipe(
filter((evt): evt is VersionReadyEvent => evt.type === 'VERSION_READY'),
map(evt => ({
type: 'UPDATE_AVAILABLE',
current: evt.currentVersion,
available: evt.latestVersion,
})));

I'm trying to figure out how to add the snackbar and other actions but don't have it yet. Ideas?! Thx!

**Comment by bampakoa** [comment]
Hey @VashJuan 👋

You are right! It has been deprecated in Angular 13 along with the `activated` property as indicated in the official Angular Docs website https://angular.io/guide/deprecations#angularservice-worker. I guess that you can still use it though because it has not been removed.

>The Angular framework usually makes a deprecation announcement and keeps the feature for some versions before removing it completely.

Does it work at all in your case?

**Comment by nithikpackt** [comment]
Thank you @bampakoa for the solution
